---
- name: Run role
  hosts: all
  any_errors_fatal: true
  roles:
    - prometheus.prometheus.node_exporter
  vars:
    node_exporter_version: latest
    node_exporter_textfile_dir: "/home/node_exporter"
